{
 "swagger": "2.0",
 "info": {
  "version": "1.0.0",
  "title": "Graph API Custom Connector",
  "description": "Graph Licensing Custom Connector"
 },
 "host": "graph.microsoft.com",
 "basePath": "/",
 "schemes": [
  "https"
 ],
 "paths": {
  "/v1.0/subscribedSkus": {
   "get": {
    "summary": "AvailableSKUs",
    "description": "AvailableSKUs",
    "operationId": "AvailableSKUs"
   }
  },
  "/v1.0/users/{userId}/assignLicense": {
   "post": {
    "summary": "AddRemoveLicense",
    "description": "AddRemoveLicense",
    "operationId": "AddRemoveLicense"
   }
  },
  "/v1.0/me/licenseDetails": {
   "get": {
    "summary": "GetMyLicenses",
    "description": "GetMyLicenses",
    "operationId": "GetMyLicenses"
   }
  },
  "/v1.0/users/{userId}/licenseDetails": {
   "get": {
    "summary": "GetUserLicenses",
    "description": "GetUserLicenses",
    "operationId": "GetUserLicenses"
   }
  },
  "/v1.0/users": {
   "get": {
    "summary": "GetAllUsers",
    "description": "Gets all users with other emails and manager",
    "operationId": "GetAllUsers"
   },
   "post": {
    "summary": "CreateUser",
    "description": "CreateUser",
    "operationId": "CreateUser"
   }
  },
  "/v1.0/roleManagement/directory/roleAssignments": {
   "get": {
    "summary": "GetRoleAssignmentOfUser",
    "description": "GetRoleAssignmentOfUser",
    "operationId": "GetRoleAssignmentOfUser"
   },
   "post": {
    "summary": "AddAdminRoleToUser",
    "description": "AddAdminRoleToUser",
    "operationId": "AddAdminRoleToUser"
   }
  },
  "/v1.0/roleManagement/directory/roleAssignments/{roleAssignmentId}": {
   "delete": {
    "summary": "DeleteRoleAssignment",
    "description": "DeleteRoleAssignment",
    "operationId": "DeleteRoleAssignment"
   }
  },
  "/beta/roleManagement/directory/roleAssignmentScheduleRequests": {
   "post": {
    "operationId": "AddAdminRoleWithExpiration",
    "summary": "Add Admin Role With Expiration",
    "description": "Adds admin role with expiration using managed identities"
   }
  },
  "/v1.0/groups": {
   "get": {
    "operationId": "GetGroupId",
    "description": "Returns an array of '1' if it finds a group with matching name",
    "summary": "Find Group Details"
   }
  },
  "/beta/users": {
   "get": {
    "summary": "Find MS User In PFE Tenant",
    "description": "Find MSFT User in PFECRMONLINE",
    "operationId": "FindMSUserInPFEOnline"
   }
  },
  "/v1.0/users/{userObjectId}": {
   "get": {
    "summary": "GetPFEUserDetails",
    "description": "Get user in PFECRMOnline tenant based on Microsoft email",
    "operationId": "GetPFEUserDetails"
   },
   "patch": {
    "operationId": "UpdateUser",
    "summary": "Update User",
    "description": "Can be leveraged to reset password, associate to accounts etc"
   }
  },
  "/v1.0/users/{user-id}": {
   "delete": {
    "operationId": "Delete-User",
    "summary": "Delete User"
   }
  },
  "/v1.0/users/{userPrincipalId}/manager/$ref": {},
  "/v1.0/auditLogs/directoryAudits": {
   "get": {
    "operationId": "Get-User-Creation-Info",
    "summary": "Get User Created Info",
    "description": "Queries logs to know who created user account"
   }
  },
  "/v1.0/roleManagement/directory/roleAssignmentScheduleRequests": {
   "get": {
    "summary": "GetAssignmentsExpiry",
    "description": "GetAssignmentsExpiry",
    "operationId": "GetAssignmentsExpiry"
   }
  },
  "/beta/users/{userId}": {
   "get": {
    "operationId": "GetUserDetailsV2",
    "summary": "Gets User Details"
   }
  },
  "/beta/rolemanagement/directory/transitiveRoleAssignments": {
   "get": {
    "summary": "GetRoleAssignmentOfUserV2",
    "operationId": "GetRoleAssignmentOfUserV2"
   }
  },
  "/beta/roleManagement/directory/roleDefinitions/{roleDefinitionId}": {
   "get": {
    "summary": "GetAdminRoleInfo",
    "operationId": "GetAdminRoleInfo"
   }
  },
  "/beta/users/{userId}/authentication/methods/resetTraditionalAuthenticationMethods": {
   "post": {
    "summary": "ResetMFA",
    "operationId": "ResetMFA",
    "description": "Reset MFA authetnication methods"
   }
  },
  "/v1.0/users/{userId}/authentication/methods": {},
  "/v1.0/users/{userId}/authentication/microsoftAuthenticatorMethods": {
   "get": {
    "summary": "List-Auth-Methods",
    "operationId": "List-Auth-Methods"
   }
  },
  "/v1.0/users/{userId}/authentication/microsoftAuthenticatorMethods/{methodId}": {
   "delete": {
    "summary": "Delete-Auth-Method",
    "operationId": "Delete-Auth-Method"
   }
  },
  "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/roleDefinitions": {},
  "/v1.0/roleManagement/directory/roleDefinitions": {
   "get": {
    "summary": "GetRoleDefinitions",
    "operationId": "GetRoleDefinitions"
   }
  },
  "/beta/roleManagement/directory/roleAssignmentScheduleInstances": {
   "get": {
    "summary": "GetActiveRolesExpiration",
    "operationId": "GetActiveRolesExpiration"
   }
  }
 },
 "securityDefinitions": {
  "oauth2-auth": {
   "type": "oauth2",
   "flow": "accessCode",
   "tokenUrl": "https://login.windows.net/common/oauth2/authorize",
   "scopes": {
    "https://graph.microsoft.com/Directory.ReadWrite.All https://graph.microsoft.com/User.ReadWrite.All https://graph.microsoft.com/RoleManagement.Read.All https://graph.microsoft.com/RoleManagement.ReadWrite.Directory https://graph.microsoft.com/CustomSecAttributeAssignment.ReadWrite.All https://graph.microsoft.com/CustomSecAttributeDefinition.ReadWrite.All https://graph.microsoft.com/AuditLog.Read.All https://graph.microsoft.com/UserAuthenticationMethod.ReadWrite.All": "https://graph.microsoft[...]"
   },
   "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/authorize"
  }
 },
 "security": [
  {
   "oauth2-auth": [
    "https://graph.microsoft.com/Directory.ReadWrite.All https://graph.microsoft.com/User.ReadWrite.All https://graph.microsoft.com/RoleManagement.Read.All https://graph.microsoft.com/RoleManagement.ReadWrite.Directory https://graph.microsoft.com/CustomSecAttributeAssignment.ReadWrite.All https://graph.microsoft.com/CustomSecAttributeDefinition.ReadWrite.All https://graph.microsoft.com/AuditLog.Read.All https://graph.microsoft.com/UserAuthenticationMethod.ReadWrite.All"
   ]
  }
 ],
 "tags": []
}